version: '3.8'

services:
  hedge-fund:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/hedge-fund}:main
    build: .
    container_name: hedge-fund-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Application settings
      - NODE_ENV=production
      - LOG_LEVEL=info
      - RISK_PROFILE=neutral
      - DEBATE_INTERVAL=3600
      - MAX_POSITIONS=8
      - KILL_SWITCH_ENABLED=true
      
      # Database (AWS RDS)
      - DB_SSL=true
    
    ports:
      - "${PORT:-4500}:9090"
    
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
