name: Test and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hedge_fund_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: |
        npm run test:technical-analysis
        npm run test:news
        npm run test:services
        npm run test:telegram
        npm run test:database
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: hedge_fund_test
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_SSL: false
        NODE_ENV: test

    - name: Deploy to EC2
      if: success()
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 4500
        script: |
          cd /home/ubuntu/hedge-fund
          git pull origin main
          docker-compose down
          docker-compose up --build -d
          sleep 30
          if docker-compose ps | grep -q "Up"; then
            echo "✅ Deployment successful!"
          else
            echo "❌ Deployment failed!"
            docker-compose logs
            exit 1
          fi
